"""Add description to MeetingRoom

Revision ID: 29560a54f9dc
Revises: 504c6a77a6fe
Create Date: 2024-12-06 12:52:16.246728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29560a54f9dc'
down_revision = '504c6a77a6fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetingroom', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetingroom', 'description')
    # ### end Alembic commands ###
